---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: /home/Student/Desktop/sbeliakou-vagrant-centos-6.7-x86_64.box 


suites:
  - name: default
    run_list:
      - recipe[jenkins::default]
    attributes:
